<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
 
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<style>
 
 .image {
  position: relative;
  display: inline-block;
}

.overlay {
  position: absolute;
  right: 0;
  z-index: 5;
  margin-right:30%;
  margin-top:5%;
}
 </style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
 
 
 
    <!-- DataTables CSS library -->
     

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- DataTables JS library -->
    <script type="text/javascript" src="/DataTables/datatables.min.js"></script>


 
 <?php echo $this->headMeta(); ?>
 <?php echo $this->headTitle(); ?>
 
 <?php  $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.css'); ?>


 <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap-grid.css'); ?>
 <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/DataTables/datatables.css'); ?>
 
 	
<?php echo $this->headScript() ?>

</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="<?php echo $this->url(array('controller'=>'index',
 'action'=>'index'));?>"><i>Books.net</i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->url(array('controller'=>'manage',
 'action'=>'index'));?>">modify books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->url(array('controller'=>'authors',
 'action'=>'index'));?>">Authors</a>
            </li>
            <li class="nav-item">
    
                <a class="nav-link" href="<?php echo $this->url(array('controller'=>'labels',
 'action'=>'index'));?>">Labels</a>
            </li>
        </ul>
    </nav>
    <div class="container-sm|md|lg|xl">
        <div class="content_area" >
            <div class="content"  >
                <br><br>
                <?php 
            
                    error_reporting(0);
                    $uniqid_id="create".uniqid(); 
  
                    ?>
                <center>
 
<?php echo $this->layout()->whatever; ?>
                </center>
                </div></div></div>
<div id="content">
 <h1><?php echo $this->escape($this->title); ?></h1>
 <?php echo $this->layout()->content; ?>
</div>
</body>
</html>